builds:
  - binary: mackerel-plugin-log-counter
    main: ./cmd/mackerel-plugin-log-counter
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: kazeburo
    name: mackerel-plugin-log-counter
